language: python
python:
    - 3.6
install:
    - pip install boto3
    - pip install utils
    - pip install moto
addons:
    sonarcloud:
        organization: "debbieneaeraconsulting-github"
        token:
            secure: "yxoCBM/HAOEkaROX2YDW1vudcmHPstWBVs2mSGxBve0IvJS7e+vAdgCUlBA0PxzfBYr3MAgzPaYA6Nuilg4o6DauHO5nMi5lA8LTHU9AkuupLzEiB+ZWHB9rPDNrBWG2REK42C4jkZsiKOmteCcpVRYE18XpLQH7Z/PszmswR8flRZ+cA1OP9ZxNQvIsGjJwPYZu7OB+vQe/VLL45vVkgXhcm4jv1Do/j7uyUlZywLeGA9MAcL8aZKsAOgUL14exV3KZXdZBpOCs96uYY1R3RJYO8ThEO+B/Xyo/lSauRK73V5MltadQbaeDJBlpVLpNnyNBZTTsvYyGntFJqdjUFcvxvsAmL9YkdEi+VMCING1okIN5e2l0imv/cL8oftwIUj/P7oqlbYivxR8bF8g1Jxo0SB/Gi0w9g7sl9ymYN2hgUpKBu8irqkXjmcS0xmhhRWmJyiH0hLur9p6R38USb3ltuDv5cbyVQhjbZylxYKK4plVp4/p5JFriDWIqzTbTqjegAcnWBiI0Ftn/9+0C+ly2pb1mMjxPh5jJwmfAJ9xhbFA6a6eCqb+5DZtFyCKnmIuf3ScKVREeiXPBfbtPArKtZ2etaiPFVGlObpa1tcorDzIhHq7vQ0qD2nVFV8j8ubnEimy/zIO37yH1VAzyBfhQ9jZHUEKa/B5UDS5iXok="
script: 
     - python dataProcessor.py
     - sonar-scanner 