language: python
python:
    - 3.6
install:
    - pip install boto3
    - pip install utils
    - pip install moto
addons:
    sonarcloud:
        organization: "debbieneaeraconsulting-github"
        token:
            secure: "hDLM6NBItrEmD1jVe6BaShgmynHOw5SApgDiBZikZoPUzojujElmTSAbKYsh8V/oRgDpO4Y2mJpIgkjwKjlqHmhJNeshzpb9o7Ng6w+iQwWaEsMsBnXl0WnTN/gI8dpJYPnriR0DnKyPhVIvwPS7zPsQvLaf6kji5BdeKSKyS36H0fIBLvYrwq8FoluYPSXuJEuWZ9PQpDID6o+AhU04QG9ByNiUrTFv86lJdBC+NOy1xjSAmA0tIaorEOBIPecapYlNYxWxPTQHXex9xqZylIfzwSgwTjt4vKrC52wr29EyLNUkquS5gCd9Ies392OS5DsoH2/XHLZL+REulfp6FB6HXCXRqgraO6pQxOyDwk1OJVUERpZeojSQOL+NYlmp5yo4UyVY0q5EUiarkFGYKxyoHkHmVYGcvXX5Ma6SiJ47o7KExaeWuq78gEec/Gq0FYMH9yX+E8wwxqLzKlbKiXce0A5SkQn1x2Gds7U9YPBZUz8o3WYc+2uKloVbAmSDJ1juHJp097gsatJF293HkQIbvhzz0g0Jce94IMnxDoADEgBY9FsKGCdVz//NDrT0jdNlh3fMjNd4cilktlATC2URvnXiJXetpDX5bv8xiG/XcDGZU5d+vGOnV91axvFNDJuFVLBUSu+JQHjBRxIIYiq2JTrOTAomBDuwmazvwIY=" "giq3WyKYj80p9xGbMov20bRL6nl8oAy82yT5oZfc6r1hsVfDWcg2TcqEfhjJ0wmCU3VSQAOs8usw2N+ravyas336LRS7cvl5o9SBxVMQOUOraZ1FBjZOky5U1KaB6JnTrKBnhzkcAy4V0LxVqOnxWOx2X6NfxasJWZb/0KgyRlMd4QRKZQgpGTZ+wp3XaFJuetGRUgL8t0bFnt6A3a2lEAeoaUbndZD/AqsHZOk0/IkWbOksmgfmA3TrLijQiStQf8wfpP5+7W5A46s3wB4ckQK0SLgQFGzfm01VQXGNE1IWI8zZTwh7tRQ5jEM/WkxgjEROSBY6bt8QVPv8mHH9gMOSjKqIjX/opcQnpxGB1Vt6Efct8h55Xy91wwdNU2p/9k5KpsA/nxo3ZbYXpNYlWs5qtn7xKQtmZJJToEd2UCdEj/Q5sm0BFJbUfO4q4qGIIPUNxUaOwVmVjtMig7TuRPhbzrMgLwy+ATvZf5CZfEt6RJG6pREk7zHkqD3oM2iGCynBxI74aAMid3nXG6jZutVtRs8sndIT2PUwS464tglIolXJH3MLHidaNznZmkoTQDPMol1Zq+3GOESI3MBwWnKeiMOHjsaZt27oG/Y8VvDGx5BgdiipWHGEdHV3J0U+7CUoL+Q10u12Z3niESh7eaXljDzPjPj279jB1Vd6Em0="
script: 
     - python dataProcessor.py
     - sonar-scanner 